on:
  push:
    branches:
      - master

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    steps:
      - name: openfn deploy
        uses: midigofrank/cli-deploy-action@v0.1.12
        with:
          secret_input: ${{ secrets.OPENFN_37cb0bde_93df_4c19_b685_f0e375d36993_API_KEY }}
          config_path_input: 'openfn-37cb0bde-93df-4c19-b685-f0e375d36993-config.json'
